/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
HoaToolsAudioProcessorEditor::HoaToolsAudioProcessorEditor(HoaToolsAudioProcessor* ownerFilter, SourcesManager* aSourcesManger)
    : AudioProcessorEditor(ownerFilter)
{
    m_sources_manager = aSourcesManger;
    m_map = new MapComponent(aSourcesManger);
    addAndMakeVisible(m_map);
    startTimer (50);
    setSize(500, 500);
}

void HoaToolsAudioProcessorEditor::paint(Graphics& g)
{
    m_map->paint(g);
}


HoaToolsAudioProcessorEditor::~HoaToolsAudioProcessorEditor()
{
    delete m_map;
}

void HoaToolsAudioProcessorEditor::timerCallback()
{
    repaint();
}