/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_5EDA7A1E__
#define __PLUGINEDITOR_H_5EDA7A1E__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "Meter.h"
#include "TextBoxSlider.h"

//==============================================================================
/**
*/
class HoaMeterAudioProcessorEditor  :
    public AudioProcessorEditor,
    public Timer,
    public ChangeListener,
    public AudioProcessorListener
{
public:
    HoaMeterAudioProcessorEditor (HoaMeterAudioProcessor* ownerFilter);
    ~HoaMeterAudioProcessorEditor();
    
    void changeListenerCallback (ChangeBroadcaster* source);
    void audioProcessorParameterChanged (AudioProcessor *processor, int parameterIndex, float newValue);
    void audioProcessorChanged (AudioProcessor *processor);
    void audioProcessorParameterChangeGestureBegin (AudioProcessor *processor, int parameterIndex);
    void audioProcessorParameterChangeGestureEnd (AudioProcessor *processor, int parameterIndex);
    void checkAllProcessorValues();
    
private:
    Image bg;
    TextBoxSlider speakerOffset_Slider;
    Meter theMeter;
    int m_nbSpeakers;
    
    void timerCallback();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
    void resized();
    
    HoaMeterAudioProcessor* getProcessor() const
    {
        return static_cast <HoaMeterAudioProcessor*> (getAudioProcessor());
    }
};


#endif  // __PLUGINEDITOR_H_5EDA7A1E__
