/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"

//==============================================================================
HoaplugAudioProcessorEditor::HoaplugAudioProcessorEditor (HoaplugAudioProcessor* ownerFilter)
    : AudioProcessorEditor (ownerFilter),
    speakerOffset_Slider ("speakerOffset"),
    speakerDistance_Slider ("speakerDistance"),
    nbSources_Label("nbSources"),
    nbSpeakers_Label("nbSpeakers")
{
    bg = ImageCache::getFromMemory (BinaryData::background_jpg, BinaryData::background_jpgSize);
    
    addAndMakeVisible (&nbSources_Label);
    addAndMakeVisible (&nbSpeakers_Label);
    
    //add the draggable-number-box sliders :
    addAndMakeVisible (&speakerOffset_Slider);
    speakerOffset_Slider.addChangeListener(this);
    speakerOffset_Slider.setRange(-180, 180, 0.5);
    
    addAndMakeVisible (&speakerDistance_Slider);
    speakerDistance_Slider.addChangeListener(this);
    speakerDistance_Slider.setRange(0., 1., 0.01);
    
    // add the HoaMap component
    addAndMakeVisible (&theMap);
    theMap.addChangeListener(this);
    
    updateMouseCursor ();
    
    // Setting size of our plug :
    setSize (580, 420);
    
    // start a timer to check peridiocally if any value of the processor has changed
    startTimer (50);
    
    getProcessor()->addListener(this);
    getProcessor()->addChangeListener(this);
}

HoaplugAudioProcessorEditor::~HoaplugAudioProcessorEditor()
{
    speakerOffset_Slider.removeChangeListener(this);
    speakerDistance_Slider.removeChangeListener(this);
    theMap.removeAllChangeListeners();
    getProcessor()->removeListener(this);
}

//==============================================================================
void HoaplugAudioProcessorEditor::paint (Graphics& g)
{
    g.drawImage(bg, 0, 0, bg.getWidth(), bg.getHeight(), 0, 0, bg.getWidth(), bg.getHeight());
    nbSources_Label.setBounds (getWidth()-159, 216, 58, 23);
    nbSpeakers_Label.setBounds (getWidth()-80, 216, 58, 23);
    speakerOffset_Slider.setBounds (getWidth()-80, 278, 62, 23);
    speakerDistance_Slider.setBounds (getWidth()-80, 347, 60, 23);    
    theMap.setBounds (10, 10, 400, 400);
}

void HoaplugAudioProcessorEditor::audioProcessorParameterChanged (AudioProcessor *processor, int parameterIndex, float newValue)
{
    HoaplugAudioProcessor* ourProcessor = getProcessor();
    
    if (parameterIndex < 2)
    {
        if (parameterIndex == HoaplugAudioProcessor::m_distance_of_loudspeakers_parameter) {
            speakerDistance_Slider.setValue (ourProcessor->getScaledParameter(parameterIndex), dontSendNotification);
            theMap.setSpeakerDistance(ourProcessor->getScaledParameter(parameterIndex));
        }
        else if (parameterIndex == HoaplugAudioProcessor::m_offset_of_loudspeakers_parameter) {
            speakerOffset_Slider.setValue (ourProcessor->getScaledParameter(parameterIndex), dontSendNotification);
            theMap.setSpeakerOffset(ourProcessor->getScaledParameter(parameterIndex));
        }
    }
    else
    {
        int indexBis;
        if(parameterIndex%2 == 0)
        {
            indexBis = ((parameterIndex-2)/2);
            theMap.setSourceAbscissa(indexBis, ourProcessor->getScaledParameter(parameterIndex), dontSendNotification);
        }
        else
        {
            indexBis = ((parameterIndex-3)/2);
            theMap.setSourceOrdinate(indexBis, ourProcessor->getScaledParameter(parameterIndex), dontSendNotification);
        }
    }
}
void HoaplugAudioProcessorEditor::audioProcessorChanged (AudioProcessor *processor)
{
    ;
}

void HoaplugAudioProcessorEditor::audioProcessorParameterChangeGestureBegin (AudioProcessor *processor, int parameterIndex)
{
    ;
}
void HoaplugAudioProcessorEditor::audioProcessorParameterChangeGestureEnd (AudioProcessor *processor, int parameterIndex)
{
    ;
}

void HoaplugAudioProcessorEditor::timerCallback()
{
    
    HoaplugAudioProcessor* ourProcessor = getProcessor();
    m_nbSources = ourProcessor->m_number_of_sources;
    m_nbSpeakers = ourProcessor->m_number_of_loudspeakers;
    
    theMap.setNbSources(m_nbSources, dontSendNotification);
    nbSources_Label.setText(String(m_nbSources), false);
    theMap.setNbSpeakers(m_nbSpeakers, dontSendNotification);
    nbSpeakers_Label.setText(String(m_nbSpeakers), false);
}

void HoaplugAudioProcessorEditor::valueChanged (Value& value)
{
    ;
}

void HoaplugAudioProcessorEditor::changeListenerCallback (ChangeBroadcaster* source)
{
    //getProcessor()->beginParameterChangeGesture	(0);
    //getProcessor()->endParameterChangeGesture(slider->getName().getIntValue());

    if (source == &theMap) {
        for (int i = 0; i < m_nbSources; i++)
        {
            getProcessor()->setParameterNotifyingHost ( i*2+2, (float) (theMap.getSourceAbscissa(i) + 1) * 0.5);
            getProcessor()->setParameterNotifyingHost ( i*2+3, (float) (theMap.getSourceOrdinate(i) + 1) * 0.5);
        }
    }
    else if (source == &speakerOffset_Slider) {
        theMap.setSpeakerOffset(speakerOffset_Slider.getValue(), dontSendNotification);
        getProcessor()->setParameterNotifyingHost (HoaplugAudioProcessor::m_offset_of_loudspeakers_parameter, (float) (speakerOffset_Slider.getValue()+ 180)/360);
    }
    else if (source == &speakerDistance_Slider) {
        theMap.setSpeakerDistance(speakerDistance_Slider.getValue(), dontSendNotification);
        getProcessor()->setParameterNotifyingHost (HoaplugAudioProcessor::m_distance_of_loudspeakers_parameter, (float) speakerDistance_Slider.getValue());
    }
}

