#!/bin/bash

VERSION="1.1"
LIBRARY="HoaLibrary"

PACKMAX5="$LIBRARY-max5"
PACKMAX6="$LIBRARY-max6"
DISTRIBMAX5="$PACKMAX5-$VERSION"
DISTRIBMAX6="$PACKMAX6-$VERSION"
UNINSTALLERMAX5="$PACKMAX5-Uninstaller.command"
UNINSTALLERMAX6="$PACKMAX6-Uninstaller.command"
MAXPACK5="../../../MaxMsp/Max5"
MAXPACK6="../../../MaxMsp/Max6"
HRTFPACK="../../../MaxMsp/HrtfDatabase"
MANUALZIP="$LIBRARY-$VERSION-Manual"

## Installer Max5 
rm $PACKMAX5.pkg
/Applications/PackageMaker.app/Contents/MacOS/packagemaker --verbose --doc $PACKMAX5.pmdoc --out $PACKMAX5.pkg
rm $DISTRIBMAX5.dmg

mkdir -p $DISTRIBMAX5
cp -pR $PACKMAX5.pkg $DISTRIBMAX5
cp -pR license.rtf $DISTRIBMAX5
cp -pR README.txt $DISTRIBMAX5
cp -pR $UNINSTALLERMAX5 $DISTRIBMAX5

hdiutil create $DISTRIBMAX5.dmg -srcfolder $DISTRIBMAX5

rm -rf $DISTRIBMAX5
rm -rf $PACKMAX5.pkg

## Installer Max6
rm $PACKMAX6.pkg
/Applications/PackageMaker.app/Contents/MacOS/packagemaker --verbose --doc $PACKMAX6.pmdoc --out $PACKMAX6.pkg
rm $DISTRIBMAX6.dmg

mkdir -p $DISTRIBMAX6
cp -pR $PACKMAX6.pkg $DISTRIBMAX6
cp -pR license.rtf $DISTRIBMAX6
cp -pR README.txt $DISTRIBMAX6
cp -pR $UNINSTALLERMAX6 $DISTRIBMAX6

hdiutil create $DISTRIBMAX6.dmg -srcfolder $DISTRIBMAX6

rm -rf $DISTRIBMAX6
rm -rf $PACKMAX6.pkg

## Manual Max5-6

mkdir $MANUALZIP
cp -pR $MAXPACK5 $MANUALZIP/$LIBRARY-max5/
cp -pR $MAXPACK6 $MANUALZIP/$LIBRARY-max6/
cp -pR $HRTFPACK $MANUALZIP/HrtfDatabase/
cp -pR license.rtf $MANUALZIP
cp -pR README.txt $MANUALZIP
cp -pR $UNINSTALLERMAX6 $MANUALZIP
cp -pR $UNINSTALLERMAX5 $MANUALZIP
ditto -ck --rsrc --sequesterRsrc $MANUALZIP $MANUALZIP.zip
rm -rf $MANUALZIP

## Move all
mkdir $LIBRARY
mv $DISTRIBMAX5.dmg $LIBRARY
mv $DISTRIBMAX6.dmg $LIBRARY
mv $MANUALZIP.zip $LIBRARY






