/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_8F6D6672__
#define __PLUGINEDITOR_H_8F6D6672__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class HoaplugAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    HoaplugAudioProcessorEditor (HoaplugAudioProcessor* ownerFilter);
    ~HoaplugAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
};


#endif  // __PLUGINEDITOR_H_8F6D6672__
